/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class ManageForm extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
    private Object tableModel;
    public ManageForm() {
        initComponents();
        jack();
        fetch();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MshipPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("MshipPU").createEntityManager();
        membershipQuery = java.beans.Beans.isDesignTime() ? null : MshipPUEntityManager.createQuery("SELECT m FROM Membership m");
        membershipList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : membershipQuery.getResultList();
        membershipQuery1 = java.beans.Beans.isDesignTime() ? null : MshipPUEntityManager.createQuery("SELECT m FROM Membership m");
        membershipList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : membershipQuery1.getResultList();
        membershipQuery2 = java.beans.Beans.isDesignTime() ? null : MshipPUEntityManager.createQuery("SELECT m FROM Membership m");
        membershipList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : membershipQuery2.getResultList();
        jPanel1 = new javax.swing.JPanel();
        man_del = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        man_lname = new javax.swing.JTextField();
        man_update = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        man_fname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        man_Age = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        man_ID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        man_cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        man_yearlevel = new javax.swing.JComboBox();
        man_course = new javax.swing.JComboBox();
        man_currentschool = new javax.swing.JTextField();
        man_civilstatus = new javax.swing.JComboBox();
        man_female = new javax.swing.JRadioButton();
        man_male = new javax.swing.JRadioButton();
        man_address = new javax.swing.JTextField();
        man_mname = new javax.swing.JTextField();
        man_nname = new javax.swing.JTextField();
        man_search = new javax.swing.JButton();
        man_searchbar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        man_del.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        man_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_edit-delete_118920 (1).png"))); // NOI18N
        man_del.setText("DELETE");
        man_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_delActionPerformed(evt);
            }
        });
        jPanel1.add(man_del);
        man_del.setBounds(180, 610, 120, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 130, 80, 17);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "Lastname", "Middlename", "Nickname", "Address", "Gender", "Age", "Civilstatus", "Currentschool", "Course", "Yearlevel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 120, 680, 560);

        man_lname.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(man_lname);
        man_lname.setBounds(220, 155, 180, 30);

        man_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        man_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Update_984748 (1).png"))); // NOI18N
        man_update.setText("UPDATE");
        man_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_updateActionPerformed(evt);
            }
        });
        jPanel1.add(man_update);
        man_update.setBounds(50, 610, 120, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Gender");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 340, 50, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setText("MANAGE MEMBERS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 30, 270, 40);

        man_fname.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(man_fname);
        man_fname.setBounds(220, 115, 180, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Year Level");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 550, 70, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Course/Acadamic Tracks");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 510, 171, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Current School");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 470, 104, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Civil Status");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 430, 76, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 380, 30, 17);
        jPanel1.add(man_Age);
        man_Age.setBounds(220, 370, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 290, 56, 17);

        man_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_IDActionPerformed(evt);
            }
        });
        jPanel1.add(man_ID);
        man_ID.setBounds(220, 70, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Member ID");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(120, 80, 80, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Middle Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 210, 88, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nickname");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 250, 67, 17);

        man_cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        man_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Delete_1493279.png"))); // NOI18N
        man_cancel.setText("CANCEL");
        man_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(man_cancel);
        man_cancel.setBounds(310, 610, 120, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 170, 73, 17);

        man_yearlevel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        man_yearlevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----Select----", " ", "Grade 11", "Grade12", "1st Year ", "2nd Year", "3rd Year", "4th Year", "5th Year", "Higher Year" }));
        jPanel1.add(man_yearlevel);
        man_yearlevel.setBounds(220, 540, 160, 30);

        man_course.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        man_course.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----Select----", " ", "Accounting", "Architecture", "Business Administration", "Chemical Engineering", "Civil Engineering", "Computer Engineering", "Computer Science", "Criminology", "Dentistry", "Education", "Electrical Engineering", "HRM", "HRS", "Information Technology", "Law", "Liberal Arts", "Mechanical Engineering", "Medical Technoloy", "Nursing", "Psychology", "Tourism", "ABM", "GAS", "HUMSS", "STEM" }));
        man_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_courseActionPerformed(evt);
            }
        });
        jPanel1.add(man_course);
        man_course.setBounds(220, 500, 160, 30);

        man_currentschool.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(man_currentschool);
        man_currentschool.setBounds(220, 460, 170, 30);

        man_civilstatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        man_civilstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----Select----", " ", "Single", "Married", "Widowed", "Separate" }));
        jPanel1.add(man_civilstatus);
        man_civilstatus.setBounds(220, 420, 130, 30);

        man_female.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        man_female.setText("Female");
        man_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(man_female);
        man_female.setBounds(300, 330, 70, 23);

        man_male.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        man_male.setText("Male");
        man_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_maleActionPerformed(evt);
            }
        });
        jPanel1.add(man_male);
        man_male.setBounds(220, 330, 60, 23);

        man_address.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(man_address);
        man_address.setBounds(220, 275, 180, 30);

        man_mname.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(man_mname);
        man_mname.setBounds(220, 195, 180, 30);

        man_nname.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(man_nname);
        man_nname.setBounds(220, 235, 180, 30);

        man_search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        man_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_search_322497.png"))); // NOI18N
        man_search.setText("Search");
        man_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                man_searchActionPerformed(evt);
            }
        });
        jPanel1.add(man_search);
        man_search.setBounds(730, 60, 110, 40);

        man_searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                man_searchbarKeyReleased(evt);
            }
        });
        jPanel1.add(man_searchbar);
        man_searchbar.setBounds(850, 70, 230, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void man_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_maleActionPerformed
        if (man_male.isSelected()){
            man_female.setSelected(false);
        }

    }//GEN-LAST:event_man_maleActionPerformed

    private void man_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_femaleActionPerformed
        if (man_female.isSelected()){
            man_male.setSelected(false);
    }//GEN-LAST:event_man_femaleActionPerformed
    }
    private void man_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_cancelActionPerformed
        UBCform ubc = new UBCform();
        ubc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_man_cancelActionPerformed

    private void man_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_updateActionPerformed
                
                try {
                     
            String id = man_ID.getText();
            int newID= Integer.parseInt(id);
            String first =  man_fname.getText();
            String last =   man_lname.getText();
            String middle = man_mname.getText();
            
            String nick =  man_nname.getText();
            String address = man_address.getText();
            String current =man_currentschool.getText();
            String course = (String) man_course.getSelectedItem();
            String civil =(String) man_civilstatus.getSelectedItem();
            String year =(String) man_yearlevel.getSelectedItem();
            String age = man_Age.getText();
                 
             String gender = "Male";
     
                 String gender1 = "Female";
      
              String sql = ("Update Membership set ID= '"+id+"', fname='"+first+"', lname='"+last+"', mname='"+middle+"', nname='"+nick+"', Address='"+address+"', Gender='"+gender+"', Age='"+age+"', Civilstatus='"+civil+"', Currentschool='"+current+"', Course='"+course+"', Yearlevel='"+year+"'");
                JOptionPane.showMessageDialog(null, "Updated");
                jack();      
                } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }               
    }//GEN-LAST:event_man_updateActionPerformed
    
    private void man_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_delActionPerformed
      
////     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
////     
     try{
////          int SelectedRowIndex = jTable1.getSelectedRow();
////            model.removeRow(SelectedRowIndex);
////           
////    
////     
     
//     
//     man_fname.setText("");
//                man_lname.setText("");
//                man_mname.setText("");
//                man_nname.setText("");
//                man_address.setText("");
//                man_currentschool.setText("");
//                man_course.setSelectedIndex(0);
//                man_civilstatus.setSelectedIndex(0);
//                man_yearlevel.setSelectedIndex(0);
//                man_Age.setText("");
//                man_female.setSelected(false);
//                man_male.setSelected(false);
stmt.executeUpdate("Delete from membership where id=" +man_ID.getText()+"");
 JOptionPane.showMessageDialog(null, "Deleted");
 jack();
                 
                
         }catch (Exception ex){
             JOptionPane.showMessageDialog(null, ex);
         } 

      
    
          
                   
    }//GEN-LAST:event_man_delActionPerformed
    
    private void man_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_IDActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_man_IDActionPerformed

    private void man_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_man_courseActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        
      
        man_ID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        man_fname.setText(model.getValueAt(selectedRowIndex, 1).toString());
        man_lname.setText(model.getValueAt(selectedRowIndex, 2).toString());
        man_mname.setText(model.getValueAt(selectedRowIndex, 3).toString());
        man_nname.setText(model.getValueAt(selectedRowIndex, 4).toString());
        man_address.setText(model.getValueAt(selectedRowIndex,5).toString());
        String gender = model.getValueAt(selectedRowIndex,6).toString();
            if (gender.equals("Male")) {
                man_male.setSelected(true);
            }
            else{
                man_female.setSelected(true);
            }
        man_Age.setText(model.getValueAt(selectedRowIndex, 7).toString());
        man_civilstatus.setSelectedItem(model.getValueAt(selectedRowIndex, 8).toString());
        man_currentschool.setText(model.getValueAt(selectedRowIndex, 9).toString());
        man_course.setSelectedItem(model.getValueAt(selectedRowIndex, 10).toString());
        man_yearlevel.setSelectedItem(model.getValueAt(selectedRowIndex, 11).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void man_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_man_searchActionPerformed
       
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String search = man_searchbar.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("Select * from Membership where id="+ man_ID.getText() +""));
        

     
    }//GEN-LAST:event_man_searchActionPerformed

    private void man_searchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_man_searchbarKeyReleased
        
    }//GEN-LAST:event_man_searchbarKeyReleased
                    
         public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager MshipPUEntityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField man_Age;
    private javax.swing.JTextField man_ID;
    private javax.swing.JTextField man_address;
    private javax.swing.JButton man_cancel;
    private javax.swing.JComboBox man_civilstatus;
    private javax.swing.JComboBox man_course;
    private javax.swing.JTextField man_currentschool;
    private javax.swing.JButton man_del;
    private javax.swing.JRadioButton man_female;
    private javax.swing.JTextField man_fname;
    private javax.swing.JTextField man_lname;
    private javax.swing.JRadioButton man_male;
    private javax.swing.JTextField man_mname;
    private javax.swing.JTextField man_nname;
    private javax.swing.JButton man_search;
    private javax.swing.JTextField man_searchbar;
    private javax.swing.JButton man_update;
    private javax.swing.JComboBox man_yearlevel;
    private java.util.List<login.Membership> membershipList;
    private java.util.List<login.Membership> membershipList1;
    private java.util.List<login.Membership> membershipList2;
    private javax.persistence.Query membershipQuery;
    private javax.persistence.Query membershipQuery1;
    private javax.persistence.Query membershipQuery2;
    // End of variables declaration//GEN-END:variables

    private void jack() {
         man_ID.setEditable(false);
           try {      
        String host = "jdbc:derby://localhost:1527/Mship";
        String uName = "admins";
        String uPass = "admins";
        con = DriverManager.getConnection(host, uName, uPass);
        
        stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        String sql = "select * from Membership";
        rs = stmt.executeQuery(sql);
    }   catch (SQLException ex) {
            
    }

    }

    private void fetch() {
        
        try {
            
            String sql = "Select * from Membership";
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        
        
    }

    }

    private void updateTable() {
        
    }
 
}
 

    

 


    
        


  

