/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class neww extends javax.swing.JFrame {

   Connection con;
    Statement stmt;
    ResultSet rs;
    int curRow = 0;
    public neww() {
        initComponents();
        jack();
        JRadioButton_male.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JTextField_fname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JTextField_lname = new javax.swing.JTextField();
        JTextField_nname = new javax.swing.JTextField();
        JTextField_mname = new javax.swing.JTextField();
        JTextField_address = new javax.swing.JTextField();
        JRadioButton_male = new javax.swing.JRadioButton();
        JComboBox_civilstatus = new javax.swing.JComboBox();
        JRadioButton_female = new javax.swing.JRadioButton();
        JTextField_currentschool = new javax.swing.JTextField();
        JComboBox_course = new javax.swing.JComboBox();
        JComboBox_yearlevel = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        JTextField_ID = new javax.swing.JTextField();
        JTextField_Age = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("NEW MEMBER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(142, 11, 171, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(96, 105, 74, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(96, 144, 80, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Middle Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(84, 200, 88, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nickname");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(101, 244, 70, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(112, 287, 60, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(137, 388, 50, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Civil Status");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(94, 442, 80, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Current School");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(68, 495, 104, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Course/Acadamic Tracks");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(27, 539, 190, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Year Level");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(115, 587, 80, 17);

        JTextField_fname.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(JTextField_fname);
        JTextField_fname.setBounds(235, 103, 174, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Gender");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(116, 334, 60, 17);

        JTextField_lname.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(JTextField_lname);
        JTextField_lname.setBounds(235, 146, 174, 30);

        JTextField_nname.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(JTextField_nname);
        JTextField_nname.setBounds(235, 236, 174, 30);

        JTextField_mname.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(JTextField_mname);
        JTextField_mname.setBounds(235, 192, 174, 30);

        JTextField_address.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(JTextField_address);
        JTextField_address.setBounds(235, 279, 174, 30);

        JRadioButton_male.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JRadioButton_male.setText("Male");
        JRadioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioButton_maleActionPerformed(evt);
            }
        });
        jPanel1.add(JRadioButton_male);
        JRadioButton_male.setBounds(235, 333, 49, 23);

        JComboBox_civilstatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JComboBox_civilstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Single", "Married", "Widowed", "Separate" }));
        jPanel1.add(JComboBox_civilstatus);
        JComboBox_civilstatus.setBounds(240, 430, 143, 30);

        JRadioButton_female.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JRadioButton_female.setText("Female");
        JRadioButton_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioButton_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(JRadioButton_female);
        JRadioButton_female.setBounds(300, 333, 70, 23);

        JTextField_currentschool.setPreferredSize(new java.awt.Dimension(59, 25));
        jPanel1.add(JTextField_currentschool);
        JTextField_currentschool.setBounds(240, 480, 174, 30);

        JComboBox_course.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JComboBox_course.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Accounting", "Architecture", "Business Administration", "Chemical Engineering", "Civil Engineering", "Computer Engineering", "Computer Science", "Criminology", "Dentistry", "Education", "Electrical Engineering", "HRM", "HRS", "Information Technology", "Law", "Liberal Arts", "Mechanical Engineering", "Medical Technoloy", "Nursing", "Psychology", "Tourism", "ABM", "GAS", "HUMSS", "STEM" }));
        jPanel1.add(JComboBox_course);
        JComboBox_course.setBounds(240, 530, 174, 30);

        JComboBox_yearlevel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JComboBox_yearlevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Grade 11", "Grade12", "1st Year", "2nd Year", "3rd Year", "4th Year", "5th Year", "Higher Year" }));
        jPanel1.add(JComboBox_yearlevel);
        JComboBox_yearlevel.setBounds(240, 580, 174, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Member ID");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(93, 68, 80, 17);
        jPanel1.add(JTextField_ID);
        JTextField_ID.setBounds(235, 65, 67, 30);
        jPanel1.add(JTextField_Age);
        JTextField_Age.setBounds(240, 380, 70, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_icons_add_1564491.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 640, 95, 56);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Delete_1493279.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(250, 640, 120, 56);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRadioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioButton_maleActionPerformed
        if (JRadioButton_male.isSelected()){
            JRadioButton_female.setSelected(false);
        }

    }//GEN-LAST:event_JRadioButton_maleActionPerformed

    private void JRadioButton_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioButton_femaleActionPerformed
        if (JRadioButton_female.isSelected()){
            JRadioButton_male.setSelected(false);
        }
    }//GEN-LAST:event_JRadioButton_femaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
        String id = JTextField_ID.getText();
        int newID= Integer.parseInt(id);
        String first =  JTextField_fname.getText();
        String last =JTextField_lname.getText();
        String middle = JTextField_mname.getText();

        String nick =  JTextField_nname.getText();
        String address = JTextField_address.getText();
        String current =JTextField_currentschool.getText();
        String course = (String) JComboBox_course.getSelectedItem();
        String civil =(String) JComboBox_civilstatus.getSelectedItem();
        String year =(String) JComboBox_yearlevel.getSelectedItem();
        String age = JTextField_Age.getText();
    
    
        String gender = "Male";
     
            String gender1 = "Female";
      
    
            try {
                
                rs.moveToInsertRow();
                rs.updateInt("ID", newID);
                  rs.updateString("fname", first);
                rs.updateString("lname", last);
                  rs.updateString("mname", middle);
              rs.updateString("nname", nick);
              
                  rs.updateString("address", address);
                  if(JRadioButton_male.isSelected()==true){
                rs.updateString("gender", gender);
                  }
                  else{
                        rs.updateString("gender", gender1);
                  }
                  rs.updateString("age", age);
                  rs.updateString("civilstatus", civil);
             
                rs.updateString("currentschool", current);
                   rs.updateString("course", course);
              
                rs.updateString("yearlevel", year);
              
                rs.insertRow();
              
                  rs.close();
                 
                JOptionPane.showMessageDialog(null, "New Member Added");
              
              jack();

                JTextField_fname.setText("");
                JTextField_lname.setText("");
                JTextField_mname.setText("");
                JTextField_nname.setText("");
                JTextField_address.setText("");
                JTextField_currentschool.setText("");
                JComboBox_course.setSelectedIndex(0);
                JComboBox_civilstatus.setSelectedIndex(0);
                JComboBox_yearlevel.setSelectedIndex(0);
                JTextField_Age.setText("");
                JRadioButton_female.setSelected(false);
                JRadioButton_male.setSelected(false);
                {
                    int result;
               rs.last();
        int id_col = rs.getInt("ID");
        String idss = Integer.toString(id_col);
       
        result = id_col+1;
     JTextField_ID.setText(String.valueOf(result));}
                

            }catch(SQLException err){
                System.out.println(err.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new UBCform().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(neww.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(neww.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(neww.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(neww.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new neww().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComboBox_civilstatus;
    private javax.swing.JComboBox JComboBox_course;
    private javax.swing.JComboBox JComboBox_yearlevel;
    private javax.swing.JRadioButton JRadioButton_female;
    private javax.swing.JRadioButton JRadioButton_male;
    private javax.swing.JTextField JTextField_Age;
    private javax.swing.JTextField JTextField_ID;
    private javax.swing.JTextField JTextField_address;
    private javax.swing.JTextField JTextField_currentschool;
    private javax.swing.JTextField JTextField_fname;
    private javax.swing.JTextField JTextField_lname;
    private javax.swing.JTextField JTextField_mname;
    private javax.swing.JTextField JTextField_nname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void jack() {
        JTextField_ID.setEditable(false);
           try {      
        String host = "jdbc:derby://localhost:1527/Mship";
        String uName = "admins";
        String uPass = "admins";
        con = DriverManager.getConnection(host, uName, uPass);
        
        stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        String sql = "select * from Membership";
        rs = stmt.executeQuery(sql);
         
        {
                    int result;
               rs.last();
        int id_col = rs.getInt("ID");
        String idss = Integer.toString(id_col);
       
        result = id_col+1;
     JTextField_ID.setText(String.valueOf(result));}
        
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
}
